apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
  # Protect the /metrics endpoint by putting it behind auth. Only one of
  # manager_auth_proxy_patch.yaml and manager_prometheus_metrics_patch.yaml should be enabled.
patchesStrategicMerge:
- manager_pull_policy.yaml
- manager_auth_proxy_patch.yaml
images:
- name: controller
  newName: docker.io/dippynark/cluster-api-kubernetes-controller
  newTag: dev
