images:
# Use `make docker-build` to build this image
- name: docker.io/dippynark/cluster-api-kubernetes-controller:dev
  loadBehavior: mustLoad
# Use `make e2e_pull` to retrieve these images
- name: gcr.io/k8s-staging-cluster-api/cluster-api-controller:v0.3.15
  loadBehavior: tryLoad
- name: gcr.io/k8s-staging-cluster-api/kubeadm-bootstrap-controller:v0.3.15
  loadBehavior: tryLoad
- name: gcr.io/k8s-staging-cluster-api/kubeadm-control-plane-controller:v0.3.15
  loadBehavior: tryLoad
- name: quay.io/jetstack/cert-manager-webhook:v1.1.0
  loadBehavior: tryLoad
- name: quay.io/jetstack/cert-manager-controller:v1.1.0
  loadBehavior: tryLoad
- name: quay.io/jetstack/cert-manager-cainjector:v1.1.0
  loadBehavior: tryLoad
- name: kindest/node:v1.20.2
  loadBehavior: tryLoad

providers:
- name: cluster-api
  type: CoreProvider
  versions:
  - name: v0.3.15
    # Use manifest from source files
    value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.15/core-components.yaml"
    type: "url"
    replacements:
    - old: "imagePullPolicy: Always"
      new: "imagePullPolicy: IfNotPresent"
    - old: "--enable-leader-election"
      new: "--enable-leader-election=false"
- name: kubeadm
  type: BootstrapProvider
  versions:
  - name: v0.3.15
    # Use manifest from source files
    value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.15/bootstrap-components.yaml"
    type: "url"
    replacements:
    - old: "imagePullPolicy: Always"
      new: "imagePullPolicy: IfNotPresent"
    - old: "--enable-leader-election"
      new: "--enable-leader-election=false"
- name: kubeadm
  type: ControlPlaneProvider
  versions:
  - name: v0.3.15
    # Use manifest from source files
    value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.15/control-plane-components.yaml"
    type: "url"
    replacements:
    - old: "imagePullPolicy: Always"
      new: "imagePullPolicy: IfNotPresent"
    - old: "--enable-leader-election"
      new: "--enable-leader-election=false"
- name: capk
  type: InfrastructureProvider
  versions:
  - name: v0.3.0
    value: "../../config"
  files:
  - sourcePath: "../data/infrastructure-kubernetes/cluster-template.yaml"
  - sourcePath: "../../release/metadata.yaml"

variables:
  KUBERNETES_VERSION: "v1.20.2"
  KUBERNETES_CONTROL_PLANE_SERVICE_TYPE: "ClusterIP"
  CNI: "./data/cni/calico/calico.yaml"
  EXP_CLUSTER_RESOURCE_SET: "true"

intervals:
  default/wait-controllers: ["3m", "10s"]
  default/wait-cluster: ["5m", "10s"]
  default/wait-control-plane: ["10m", "10s"]
  default/wait-worker-nodes: ["5m", "10s"]
  default/wait-machine-pool-nodes: ["5m", "10s"]
  default/wait-delete-cluster: ["3m", "10s"]
  default/wait-machine-upgrade: ["20m", "10s"]
  default/wait-machine-pool-upgrade: ["5m", "10s"]
  default/wait-machine-remediation: ["5m", "10s"]
  node-drain/wait-deployment-available: ["3m", "10s"]
  node-drain/wait-control-plane: ["15m", "10s"]
