namespace: capi-webhook-system

resources:
- manifests.yaml
- service.yaml
- ../certmanager
- ../manager

patchesStrategicMerge:
- manager_webhook_patch.yaml
- mutatingwebhookcainjection_patch.yaml
#- validatingwebhookcainjection_patch.yaml

configurations:
- kustomizeconfig.yaml

vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: serving-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1alpha2
    name: serving-cert
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: webhook-service
