
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infrastructure-dippynark-co-uk-v1alpha3-kubernetesmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mkubernetesmachine.kb.io
  rules:
  - apiGroups:
    - infrastructure.dippynark.co.uk
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubernetesmachines
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infrastructure-dippynark-co-uk-v1alpha2-kubernetesmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mkubernetesmachine.kb.io
  rules:
  - apiGroups:
    - infrastructure.dippynark.co.uk
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubernetesmachines
  sideEffects: None
