# permissions to do viewer kubernetesmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesmachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachinetemplates/status
  verbs:
  - get
