# permissions to do viewer kubernetesmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesmachine-viewer-role
rules:
- apiGroups:
  - infrastructure.dippynark.co.uk
  resources:
  - kubernetesmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.dippynark.co.uk
  resources:
  - kubernetesmachines/status
  verbs:
  - get
