# permissions to do edit kubernetesmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesmachine-editor-role
rules:
- apiGroups:
  - infrastructure.dippynark.co.uk
  resources:
  - kubernetesmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.dippynark.co.uk
  resources:
  - kubernetesmachines/status
  verbs:
  - get
  - patch
  - update
