# permissions to do edit kubernetesmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesmachinetemplate-editor-role
rules:
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachinetemplates/status
  verbs:
  - get
  - patch
  - update
