
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachines/status
  verbs:
  - get
  - patch
  - update
