# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubernetesmachines.infrastructure.lukeaddison.co.uk
spec:
  conversion:
    strategy: Webhook
    webhook:
      # TODO: check this is correct
      # https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.4/pkg/webhook/conversion/conversion.go#L29
      conversionReviewVersions: ["v1", "v1beta1"]
      clientConfig:
        # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
        # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
        caBundle: Cg==
        service:
          namespace: system
          name: webhook-service
          path: /convert
