---
apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
kind: KubernetesCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  controlPlaneServiceType: ${KUBERNETES_CONTROL_PLANE_SERVICE_TYPE:="ClusterIP"}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ${SERVICE_CIDR:=["10.128.0.0/12"]}
    pods:
      cidrBlocks: ${POD_CIDR:=["192.168.0.0/16"]}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
  infrastructureRef:
    apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
    kind: KubernetesCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
kind: KubernetesMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-controller
spec:
  template:
    spec:
      allowRecreation: true
      containers:
      - name: kind
        resources:
          requests:
            cpu: ${KUBERNETES_CONTROL_PLANE_MACHINE_CPU_REQUESTS:="0"}
            memory: ${KUBERNETES_CONTROL_PLANE_MACHINE_MEMORY_REQUESTS:="0"}
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
      volumeClaimTemplates:
      - metadata:
          name: var-lib-etcd
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: ${ETCD_STORAGE_SIZE:=10Gi}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
  infrastructureTemplate:
    apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
    kind: KubernetesMachineTemplate
    name: ${CLUSTER_NAME}-controller
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          cgroups-per-qos: "false"
          enforce-node-allocatable: ""
    clusterConfiguration:
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          cgroups-per-qos: "false"
          enforce-node-allocatable: ""
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
            cgroups-per-qos: "false"
            enforce-node-allocatable: ""
---
apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
kind: KubernetesMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-worker
spec:
  template:
    spec:
      containers:
      - name: kind
        resources:
          requests:
            cpu: ${KUBERNETES_NODE_MACHINE_CPU_REQUESTS:="0"}
            memory: ${KUBERNETES_NODE_MACHINE_MEMORY_REQUESTS:="0"}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          name: ${CLUSTER_NAME}
          kind: KubeadmConfigTemplate
      infrastructureRef:
        apiVersion: infrastructure.lukeaddison.co.uk/v1alpha3
        name: ${CLUSTER_NAME}-worker
        kind: KubernetesMachineTemplate
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 2m
  - type: Ready
    status: "False"
    timeout: 2m
  nodeStartupTimeout: 10m
