---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capk-capi-kubeadm-control-plane
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
    # TODO: use aggregation label when available
    # https://github.com/kubernetes-sigs/cluster-api/pull/2685
    #kubadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"
rules:
- apiGroups:
  - infrastructure.lukeaddison.co.uk
  resources:
  - kubernetesmachines
  - kubernetesmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capk-capi-kubeadm-control-plane
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capk-capi-kubeadm-control-plane
subjects:
- kind: ServiceAccount
  name: default
  namespace: capi-kubeadm-control-plane-system
