
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: kubernetesclusters.infrastructure.lukeaddison.co.uk
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: KubernetesCluster status
    name: phase
    type: string
  - JSONPath: .status.apiEndpoints[0].host
    description: Endpoint host for reaching the control plane
    name: host
    type: string
  - JSONPath: .status.apiEndpoints[0].port
    description: Endpoint port for reaching the control plane
    name: port
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  group: infrastructure.lukeaddison.co.uk
  names:
    categories:
    - cluster-api
    kind: KubernetesCluster
    listKind: KubernetesClusterList
    plural: kubernetesclusters
    singular: kubernetescluster
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: false
  - name: v1alpha3
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
