
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: kubernetesmachines.infrastructure.lukeaddison.co.uk
spec:
  group: infrastructure.lukeaddison.co.uk
  names:
    categories:
    - cluster-api
    kind: KubernetesMachine
    listKind: KubernetesMachineList
    plural: kubernetesmachines
    singular: kubernetesmachine
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KubernetesMachine is the Schema for the kubernetesmachines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KubernetesMachineSpec defines the desired state of KubernetesMachine
          properties:
            providerID:
              description: ProviderID will be the pod uid in ProviderID format (kubernetes:////<poduid>)
              type: string
          type: object
        status:
          description: KubernetesMachineStatus defines the observed state of KubernetesMachine
          properties:
            ready:
              description: Ready denotes that the machine (kubernetes pod) is ready
              type: boolean
          required:
          - ready
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
