
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: kubernetesclusters.infrastructure.lukeaddison.co.uk
spec:
  group: infrastructure.lukeaddison.co.uk
  names:
    categories:
    - cluster-api
    kind: KubernetesCluster
    listKind: KubernetesClusterList
    plural: kubernetesclusters
    singular: kubernetescluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KubernetesCluster is the Schema for the kubernetesclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KubernetesClusterSpec defines the desired state of KubernetesCluster
          properties:
            controlPlaneEndpoint:
              description: ControlPlaneEndpoint represents the endpoint used to communicate
                with the control plane.
              properties:
                host:
                  description: Host is the hostname on which the API server is serving.
                  type: string
                port:
                  description: Port is the port on which the API server is serving.
                  format: int32
                  type: integer
              required:
              - host
              - port
              type: object
            controlPlaneServiceType:
              description: Service Type string describes ingress methods for a service
              type: string
          type: object
        status:
          description: KubernetesClusterStatus defines the observed state of KubernetesCluster
          properties:
            ready:
              description: Ready denotes that the kubernetes cluster (infrastructure)
                is ready.
              type: boolean
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
