
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: kubernetesclusters.infrastructure.lukeaddison.co.uk
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: KubernetesCluster status
    name: phase
    type: string
  - JSONPath: .status.apiEndpoints[0].host
    description: Endpoint host for reaching the control plane
    name: host
    type: string
  - JSONPath: .status.apiEndpoints[0].port
    description: Endpoint port for reaching the control plane
    name: port
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  group: infrastructure.lukeaddison.co.uk
  names:
    categories:
    - cluster-api
    kind: KubernetesCluster
    listKind: KubernetesClusterList
    plural: kubernetesclusters
    singular: kubernetescluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KubernetesCluster is the Schema for the kubernetesclusters API.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KubernetesClusterSpec defines the desired state of KubernetesCluster
          properties:
            controlPlaneEndpoint:
              description: ControlPlaneEndpoint represents the endpoint used to communicate
                with the control plane.
              properties:
                host:
                  description: Host is the hostname on which the API Server is serving.
                  type: string
                port:
                  description: Port is the port on which the API Server is serving.
                  format: int32
                  type: integer
              required:
              - host
              - port
              type: object
            controlPlaneServiceType:
              description: ControlPlaneServiceType is the type of Service used for
                the control plane load balancer.
              enum:
              - ClusterIP
              - LoadBalancer
              type: string
          type: object
        status:
          description: KubernetesClusterStatus defines the observed state of a KubernetesCluster.
          properties:
            apiEndpoints:
              description: APIEndpoints represents the endpoints to communicate with
                the control plane.
              items:
                description: APIEndpoint represents a reachable Kubernetes API endpoint.
                properties:
                  host:
                    description: Host is the hostname on which the API Server is serving.
                    type: string
                  port:
                    description: Port is the port on which the API Server is serving.
                    format: int32
                    type: integer
                required:
                - host
                - port
                type: object
              type: array
            errorMessage:
              description: ErrorMessage will be set in the event that there is a terminal
                problem reconciling the KubernetesCluster and will contain a more
                verbose string suitable for logging and human consumption.
              type: string
            errorReason:
              description: ErrorReason will be set in the event that there is a terminal
                problem reconciling the KubernetesCluster and will contain a succinct
                value suitable for machine interpretation.
              type: string
            phase:
              description: Phase represents the current phase of KubernetesCluster
                actuation.
              type: string
            ready:
              description: Ready denotes that the KubernetesCluster is ready.
              type: boolean
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
